// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	db, err := NewDB()
	if err != nil {
		return nil, err
	}
	app := NewApp(db)
	return app, nil
}
